language: kotlin
sudo: false
install: true

#addons:
#  sonarcloud:
#    organization: "radixdlt-github"
#    token:
#      secure: Xq9YUi1VblOJJfXhrWpPCGOZzmJd5W8HflDSUk8xpVdnrl7N7oohFdJO0xLdnH8/zO7nGrM0P2y1JKrOBTvTo1FkoRbmtIwIqEmN6eWmdPN23xfxdgiv5lfWFyhjFByEhIJ3+ypg2MsWp+N/uKtGFvDXAhAh6aJfCLhhLrrIdhOMi1ozQ6vIhTgCvVH2PyzTmiwM8b9Mv/m0N1IPIw2JFEkVqG8334p650nSBx0pau2t7paxsBKq633okMCE/67tY3clp+/ONJinOu5egX7SXv0QYEuqehKMCz5YqZHXcpW1FwZZFJzONdm2l9jJOtla6ReiwresYXe9bMnJ5/SK32FCDQjLYj+JNQdXP+rt1jZX3/4CJCxrKwD3r0p+71yDml59XQXE1C4Ewlhl5wuSFGLUGhOvevaNULpY2+GH0vu9o5D2BC2FfFIhVEFUC5ldBVnVdl8j8ltg0n1oimjKRdh9QgjiKCph0dHakki6yv/MxPMmHwLhWpddv1hl6jIKYtYKsHE8BPFJOA47wt5IIWiGibMJRLKZ1C08coYByvrp/ADpZsZcD9oR/ZynXhCM/r6ZbJrYU5tKmzJnb48Ec4z0g7L+T4gBu+BRqUoawzFxJR5rfmmstehnQmqmyFW9RlPs+hegzgpu4owi5UK/5y5qRYh80Ig24B7gf+8qaT8="

jdk:
  - oraclejdk8

jobs:
  include:
    - stage: test
      script: ./gradlew test

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'
